baseurl: /pbsjones.github.io
title: Writing 
subtitle: About stuff.
author: pbsjones
simple_search: http://google.com/search
description: A place for writing about stuff.
name: pbsjones.github.io
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/Denver
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: neovim
git:
  branch: main
